import type {
  Program, University, ExpertiseTag, Person, Team,
  PitchSlot, Score, MentorMatch, VisaLetter
} from './types'

// ─── Expertise Tags ───────────────────────────────────────────────────────────
export const expertiseTags: ExpertiseTag[] = [
  { tagId: 'tag_01', name: 'B2B SaaS',           domain: 'Sector' },
  { tagId: 'tag_02', name: 'Consumer',            domain: 'Sector' },
  { tagId: 'tag_03', name: 'Hardware',            domain: 'Sector' },
  { tagId: 'tag_04', name: 'Climate Tech',        domain: 'Sector' },
  { tagId: 'tag_05', name: 'FinTech',             domain: 'Sector' },
  { tagId: 'tag_06', name: 'HealthTech',          domain: 'Sector' },
  { tagId: 'tag_07', name: 'EdTech',              domain: 'Sector' },
  { tagId: 'tag_08', name: 'Go-to-Market',        domain: 'Function' },
  { tagId: 'tag_09', name: 'Fundraising',         domain: 'Function' },
  { tagId: 'tag_10', name: 'Product',             domain: 'Function' },
  { tagId: 'tag_11', name: 'BD & Partnerships',   domain: 'Function' },
  { tagId: 'tag_12', name: 'AI/ML',               domain: 'Technology' },
  { tagId: 'tag_13', name: 'Ops & Scaling',       domain: 'Function' },
  { tagId: 'tag_14', name: 'Legal & Compliance',  domain: 'Function' },
  { tagId: 'tag_15', name: 'Web3',                domain: 'Sector' },
]

// ─── Programs ─────────────────────────────────────────────────────────────────
export const programs: Program[] = [
  {
    programId: 'prog_worlds_2026',
    name: 'GSSC Worlds 2026',
    type: 'Worlds',
    year: 2026,
    status: 'active',
  },
  {
    programId: 'prog_india_2025',
    name: 'GSSC India 2025',
    type: 'Regional',
    year: 2025,
    status: 'completed',
    advancesToId: 'prog_worlds_2026',
  },
  {
    programId: 'prog_korea_2025',
    name: 'GSSC Korea 2025',
    type: 'Regional',
    year: 2025,
    status: 'completed',
    advancesToId: 'prog_worlds_2026',
  },
]

// ─── Universities ─────────────────────────────────────────────────────────────
export const universities: University[] = [
  {
    universityId: 'uni_usc',
    name: 'USC',
    country: 'United States',
    activeStatus: true,
    cohortHistory: [2024, 2025, 2026],
    pocIds: [],
  },
  {
    universityId: 'uni_berkeley',
    name: 'UC Berkeley',
    country: 'United States',
    activeStatus: true,
    cohortHistory: [2025, 2026],
    pocIds: ['person_gigi'],
  },
  {
    universityId: 'uni_iitdelhi',
    name: 'IIT Delhi',
    country: 'India',
    activeStatus: true,
    cohortHistory: [2024, 2025, 2026],
    pocIds: [],
  },
  {
    universityId: 'uni_kaist',
    name: 'KAIST',
    country: 'South Korea',
    activeStatus: true,
    cohortHistory: [2024, 2025, 2026],
    pocIds: ['person_jiho'],
  },
  {
    universityId: 'uni_aalto',
    name: 'Aalto University',
    country: 'Finland',
    activeStatus: true,
    cohortHistory: [2024, 2025, 2026],
    pocIds: [],
  },
  {
    universityId: 'uni_oxford',
    name: 'University of Oxford',
    country: 'United Kingdom',
    activeStatus: true,
    cohortHistory: [2024, 2025, 2026],
    pocIds: [],
  },
  {
    universityId: 'uni_nus',
    name: 'NUS',
    country: 'Singapore',
    activeStatus: true,
    cohortHistory: [2025, 2026],
    pocIds: [],
  },
  {
    universityId: 'uni_eth',
    name: 'ETH Zurich',
    country: 'Switzerland',
    activeStatus: true,
    cohortHistory: [2025, 2026],
    pocIds: [],
  },
  {
    universityId: 'uni_tau',
    name: 'Tel Aviv University',
    country: 'Israel',
    activeStatus: true,
    cohortHistory: [2025, 2026],
    pocIds: [],
  },
  {
    universityId: 'uni_toronto',
    name: 'University of Toronto',
    country: 'Canada',
    activeStatus: true,
    cohortHistory: [2025, 2026],
    pocIds: [],
  },
  {
    universityId: 'uni_hkust',
    name: 'HKUST',
    country: 'Hong Kong',
    activeStatus: true,
    cohortHistory: [2026],
    pocIds: [],
  },
  {
    universityId: 'uni_tsinghua',
    name: 'Tsinghua University',
    country: 'China',
    activeStatus: true,
    cohortHistory: [2026],
    pocIds: [],
  },
  {
    universityId: 'uni_columbia',
    name: 'Columbia University',
    country: 'United States',
    activeStatus: true,
    cohortHistory: [2026],
    pocIds: [],
  },
  {
    universityId: 'uni_utaustin',
    name: 'UT Austin',
    country: 'United States',
    activeStatus: true,
    cohortHistory: [2026],
    pocIds: [],
  },
]

// ─── Teams ────────────────────────────────────────────────────────────────────
export const teams: Team[] = [
  // Track A — teams 1–6 (direct qualifiers)
  {
    teamId: 'team_atlix',
    teamName: 'Atlix',
    universityId: 'uni_usc',
    programId: 'prog_worlds_2026',
    pitchSummary: 'B2B SaaS platform automating enterprise procurement workflows using AI agents.',
    stage: 'Pre-seed',
    qualifyingPath: 'direct',
    needsExpertiseTagIds: ['tag_08', 'tag_01', 'tag_09'],
    memberIds: ['student_alex_ramos', 'student_mia_torres', 'student_derek_chen'],
    trackAssignment: 'A',
  },
  {
    teamId: 'team_cognate',
    teamName: 'Cognate',
    universityId: 'uni_berkeley',
    programId: 'prog_worlds_2026',
    pitchSummary: 'AI-native knowledge management tool for distributed engineering teams.',
    stage: 'Seed',
    qualifyingPath: 'direct',
    needsExpertiseTagIds: ['tag_12', 'tag_10', 'tag_01'],
    memberIds: ['student_priya_sharma', 'student_liam_nguyen'],
    trackAssignment: 'A',
  },
  {
    teamId: 'team_helion',
    teamName: 'Helion',
    universityId: 'uni_eth',
    programId: 'prog_worlds_2026',
    pitchSummary: 'Next-gen solid-state battery hardware for grid-scale energy storage.',
    stage: 'Pre-seed',
    qualifyingPath: 'direct',
    needsExpertiseTagIds: ['tag_03', 'tag_04', 'tag_09'],
    memberIds: ['student_lars_fischer', 'student_anna_mueller', 'student_tobias_braun'],
    trackAssignment: 'A',
  },
  {
    teamId: 'team_meridian',
    teamName: 'Meridian',
    universityId: 'uni_oxford',
    programId: 'prog_worlds_2026',
    pitchSummary: 'Embedded finance infrastructure for emerging market SMEs.',
    stage: 'Seed',
    qualifyingPath: 'direct',
    needsExpertiseTagIds: ['tag_05', 'tag_14', 'tag_11'],
    memberIds: ['student_james_hartley', 'student_sofia_okonkwo'],
    trackAssignment: 'A',
  },
  {
    teamId: 'team_arca',
    teamName: 'Arca',
    universityId: 'uni_nus',
    programId: 'prog_worlds_2026',
    pitchSummary: 'Social commerce app for Gen-Z fashion discovery in Southeast Asia.',
    stage: 'Pre-seed',
    qualifyingPath: 'direct',
    needsExpertiseTagIds: ['tag_02', 'tag_08', 'tag_10'],
    memberIds: ['student_wei_lin', 'student_nadia_tan', 'student_farhan_rashid'],
    trackAssignment: 'A',
  },
  {
    teamId: 'team_solace',
    teamName: 'Solace',
    universityId: 'uni_columbia',
    programId: 'prog_worlds_2026',
    pitchSummary: 'AI-powered mental health triage and care coordination platform.',
    stage: 'Pre-seed',
    qualifyingPath: 'direct',
    needsExpertiseTagIds: ['tag_06', 'tag_09', 'tag_12'],
    memberIds: ['student_elena_vasquez', 'student_omar_hassan'],
    trackAssignment: 'A',
  },
  // Track B — teams 7–11
  {
    teamId: 'team_parity',
    teamName: 'Parity',
    universityId: 'uni_utaustin',
    programId: 'prog_worlds_2026',
    pitchSummary: 'Decentralized identity protocol for cross-border credential verification.',
    stage: 'Seed',
    qualifyingPath: 'direct',
    needsExpertiseTagIds: ['tag_15', 'tag_14', 'tag_09'],
    memberIds: ['student_carlos_reyes', 'student_aisha_obi'],
    trackAssignment: 'B',
  },
  {
    teamId: 'team_luma',
    teamName: 'Luma',
    universityId: 'uni_hkust',
    programId: 'prog_worlds_2026',
    pitchSummary: 'Gamified language learning app targeting adult professionals in Asia.',
    stage: 'Pre-seed',
    qualifyingPath: 'direct',
    needsExpertiseTagIds: ['tag_02', 'tag_07', 'tag_08'],
    memberIds: ['student_felix_chan', 'student_iris_ho', 'student_kevin_lam'],
    trackAssignment: 'B',
  },
  {
    teamId: 'team_vanta',
    teamName: 'Vanta',
    universityId: 'uni_tsinghua',
    programId: 'prog_worlds_2026',
    pitchSummary: 'Enterprise AI agent orchestration platform for Fortune 500 ops automation.',
    stage: 'Seed',
    qualifyingPath: 'direct',
    needsExpertiseTagIds: ['tag_12', 'tag_01', 'tag_13'],
    memberIds: ['student_xiao_zhang', 'student_lei_wang'],
    trackAssignment: 'B',
  },
  {
    teamId: 'team_dune',
    teamName: 'Dune',
    universityId: 'uni_toronto',
    programId: 'prog_worlds_2026',
    pitchSummary: 'Carbon capture hardware deployed in commercial HVAC systems.',
    stage: 'Pre-seed',
    qualifyingPath: 'direct',
    needsExpertiseTagIds: ['tag_04', 'tag_03', 'tag_11'],
    memberIds: ['student_ethan_park', 'student_claire_martin', 'student_raj_patel'],
    trackAssignment: 'B',
  },
  {
    teamId: 'team_nexus',
    teamName: 'Nexus',
    universityId: 'uni_iitdelhi',
    programId: 'prog_worlds_2026',
    pitchSummary: 'SaaS platform for informal retail digitization across Tier-2 Indian cities.',
    stage: 'Seed',
    qualifyingPath: 'regional',
    regionLabel: 'GSSC India',
    needsExpertiseTagIds: ['tag_01', 'tag_13', 'tag_08'],
    memberIds: ['student_arjun_singh', 'student_aiko_tanaka'],
    trackAssignment: 'B',
  },
  // Track C — teams 12–16
  {
    teamId: 'team_orbit',
    teamName: 'Orbit',
    universityId: 'uni_iitdelhi',
    programId: 'prog_worlds_2026',
    pitchSummary: 'Satellite imagery analytics platform for precision agriculture in South Asia.',
    stage: 'Pre-seed',
    qualifyingPath: 'regional',
    regionLabel: 'GSSC India',
    needsExpertiseTagIds: ['tag_12', 'tag_10', 'tag_09'],
    memberIds: ['student_kavya_reddy', 'student_rohan_mehta'],
    trackAssignment: 'C',
  },
  {
    teamId: 'team_pragma',
    teamName: 'Pragma',
    universityId: 'uni_tau',
    programId: 'prog_worlds_2026',
    pitchSummary: 'AI-driven credit scoring for unbanked populations using alternative data.',
    stage: 'Pre-seed',
    qualifyingPath: 'regional',
    regionLabel: 'GSSC India',
    needsExpertiseTagIds: ['tag_05', 'tag_12', 'tag_11'],
    memberIds: ['student_noa_cohen', 'student_yael_levy', 'student_amit_katz'],
    trackAssignment: 'C',
  },
  {
    teamId: 'team_flux',
    teamName: 'Flux',
    universityId: 'uni_aalto',
    programId: 'prog_worlds_2026',
    pitchSummary: 'Modular offshore wind turbine components for rapid deployment in Nordic waters.',
    stage: 'Seed',
    qualifyingPath: 'regional',
    regionLabel: 'GSSC India',
    needsExpertiseTagIds: ['tag_04', 'tag_03', 'tag_13'],
    memberIds: ['student_mikko_virtanen', 'student_aino_leinonen'],
    trackAssignment: 'C',
  },
  {
    teamId: 'team_kirin',
    teamName: 'Kirin',
    universityId: 'uni_kaist',
    programId: 'prog_worlds_2026',
    pitchSummary: 'Smart prosthetics with embedded AI for real-time gait adaptation.',
    stage: 'Seed',
    qualifyingPath: 'regional',
    regionLabel: 'GSSC Korea',
    needsExpertiseTagIds: ['tag_03', 'tag_12', 'tag_08'],
    memberIds: ['student_joon_kim', 'student_soyeon_lee', 'student_james_park_1'],
    trackAssignment: 'C',
  },
  {
    teamId: 'team_sora',
    teamName: 'Sora',
    universityId: 'uni_kaist',
    programId: 'prog_worlds_2026',
    pitchSummary: 'Adaptive e-learning platform personalized by neuro-feedback signals.',
    stage: 'Pre-seed',
    qualifyingPath: 'regional',
    regionLabel: 'GSSC Korea',
    needsExpertiseTagIds: ['tag_02', 'tag_07', 'tag_10'],
    memberIds: ['student_hyun_cho', 'student_yuna_kim', 'student_james_park_2'],
    trackAssignment: 'C',
  },
]

// ─── Persons ──────────────────────────────────────────────────────────────────
export const persons: Person[] = [
  // ── Admins / Organizers ──
  {
    personId: 'person_mike',
    name: 'Mike Lee',
    email: 'mike@gssf.org',
    nationality: 'American',
    country: 'United States',
    roles: ['ADMIN', 'ORGANIZER'],
    status: 'confirmed',
    organization: 'GSSF/USC',
    needsVisa: false,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'person_tun',
    name: 'Tun',
    email: 'tun@gssf.org',
    nationality: 'Burmese',
    country: 'United States',
    roles: ['ADMIN', 'ORGANIZER'],
    status: 'confirmed',
    organization: 'GSSF',
    needsVisa: false,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'person_gigi',
    name: 'Gigi Wang',
    email: 'gigi@berkeley.edu',
    nationality: 'American',
    country: 'United States',
    roles: ['ORGANIZER', 'UNIVERSITY_POC'],
    status: 'confirmed',
    organization: 'UC Berkeley',
    universityId: 'uni_berkeley',
    needsVisa: false,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'person_jiho',
    name: 'Ji-ho Park',
    email: 'jiho@kaist.ac.kr',
    nationality: 'Korean',
    country: 'South Korea',
    roles: ['ORGANIZER', 'UNIVERSITY_POC'],
    status: 'confirmed',
    organization: 'KAIST',
    universityId: 'uni_kaist',
    needsVisa: false,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026', 'prog_korea_2025'],
  },

  // ── Judges ──
  {
    personId: 'judge_sarah',
    name: 'Sarah Chen',
    email: 'sarah.chen@ticketmaster.com',
    nationality: 'American',
    country: 'United States',
    roles: ['JUDGE'],
    status: 'confirmed',
    organization: 'Ticketmaster',
    needsVisa: false,
    expertise: [],
    conflictWithTeamIds: ['team_atlix', 'team_cognate'],
    conflictWithUniversityIds: [],
    rubricAck: true,
    rubricAckAt: '2026-02-15T10:00:00Z',
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'judge_marcus',
    name: 'Marcus Webb',
    email: 'marcus.webb@youtube.com',
    nationality: 'American',
    country: 'United States',
    roles: ['JUDGE'],
    status: 'confirmed',
    organization: 'YouTube Originals',
    needsVisa: false,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: true,
    rubricAckAt: '2026-02-16T14:30:00Z',
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'judge_priya',
    name: 'Priya Nair',
    email: 'priya.nair@tiktok.com',
    nationality: 'Indian',
    country: 'Singapore',
    roles: ['JUDGE'],
    status: 'confirmed',
    organization: 'TikTok Live',
    needsVisa: true,
    expertise: [],
    conflictWithTeamIds: ['team_nexus'],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'judge_daniel',
    name: 'Daniel Yoon',
    email: 'daniel.yoon@a16z.com',
    nationality: 'Korean-American',
    country: 'United States',
    roles: ['JUDGE'],
    status: 'confirmed',
    organization: 'Andreessen Horowitz',
    needsVisa: false,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: true,
    rubricAckAt: '2026-02-14T09:00:00Z',
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'judge_leila',
    name: 'Leila Ahmadi',
    email: 'leila.ahmadi@alchemist.vc',
    nationality: 'Iranian-American',
    country: 'United States',
    roles: ['JUDGE'],
    status: 'invited',
    organization: 'Alchemist Accelerator',
    needsVisa: false,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'judge_tom',
    name: 'Tom Nakamura',
    email: 'tom.nakamura@softbank.com',
    nationality: 'Japanese',
    country: 'Japan',
    roles: ['JUDGE'],
    status: 'confirmed',
    organization: 'SoftBank Vision Fund',
    needsVisa: true,
    expertise: [],
    conflictWithTeamIds: ['team_kirin'],
    conflictWithUniversityIds: [],
    rubricAck: true,
    rubricAckAt: '2026-02-17T11:00:00Z',
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },

  // ── Mentors ──
  {
    personId: 'mentor_01',
    name: 'Rachel Kim',
    email: 'rachel.kim@google.com',
    nationality: 'Korean-American',
    country: 'United States',
    roles: ['MENTOR'],
    status: 'confirmed',
    organization: 'Google',
    needsVisa: false,
    expertise: [
      { tagId: 'tag_01', level: 'Deep Expert' },
      { tagId: 'tag_08', level: 'Expert' },
      { tagId: 'tag_10', level: 'Expert' },
    ],
    geographicFocus: 'North America',
    industryVertical: 'Enterprise Software',
    yearsExperience: 14,
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'mentor_02',
    name: 'David Park',
    email: 'david.park@youtube.com',
    nationality: 'American',
    country: 'United States',
    roles: ['MENTOR'],
    status: 'confirmed',
    organization: 'YouTube',
    needsVisa: false,
    expertise: [
      { tagId: 'tag_02', level: 'Deep Expert' },
      { tagId: 'tag_08', level: 'Expert' },
      { tagId: 'tag_07', level: 'Practitioner' },
    ],
    geographicFocus: 'North America',
    industryVertical: 'Consumer Tech',
    yearsExperience: 11,
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'mentor_03',
    name: 'Samira Hassan',
    email: 'samira.hassan@duolingo.com',
    nationality: 'Egyptian',
    country: 'United States',
    roles: ['MENTOR'],
    status: 'confirmed',
    organization: 'Duolingo',
    needsVisa: false,
    expertise: [
      { tagId: 'tag_07', level: 'Deep Expert' },
      { tagId: 'tag_10', level: 'Expert' },
      { tagId: 'tag_02', level: 'Expert' },
    ],
    geographicFocus: 'North America',
    industryVertical: 'Consumer EdTech',
    yearsExperience: 9,
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'mentor_04',
    name: 'James Liu',
    email: 'james.liu@openai.com',
    nationality: 'Chinese-American',
    country: 'United States',
    roles: ['MENTOR'],
    status: 'confirmed',
    organization: 'OpenAI',
    needsVisa: false,
    expertise: [
      { tagId: 'tag_12', level: 'Deep Expert' },
      { tagId: 'tag_01', level: 'Expert' },
      { tagId: 'tag_10', level: 'Expert' },
    ],
    geographicFocus: 'North America',
    industryVertical: 'AI/ML Infra',
    yearsExperience: 12,
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'mentor_05',
    name: 'Mei Zhang',
    email: 'mei.zhang@tiktok.com',
    nationality: 'Chinese',
    country: 'Singapore',
    roles: ['MENTOR'],
    status: 'confirmed',
    organization: 'TikTok Live',
    needsVisa: true,
    expertise: [
      { tagId: 'tag_02', level: 'Deep Expert' },
      { tagId: 'tag_08', level: 'Deep Expert' },
      { tagId: 'tag_12', level: 'Expert' },
    ],
    geographicFocus: 'Southeast Asia',
    industryVertical: 'Consumer & Livestream',
    yearsExperience: 8,
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'mentor_06',
    name: 'Carlos Mendes',
    email: 'carlos.mendes@alchemist.vc',
    nationality: 'Brazilian',
    country: 'United States',
    roles: ['MENTOR'],
    status: 'confirmed',
    organization: 'Alchemist Accelerator',
    needsVisa: false,
    expertise: [
      { tagId: 'tag_01', level: 'Expert' },
      { tagId: 'tag_09', level: 'Deep Expert' },
      { tagId: 'tag_11', level: 'Expert' },
    ],
    geographicFocus: 'North America',
    industryVertical: 'B2B & Deep Tech',
    yearsExperience: 13,
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'mentor_07',
    name: 'Ananya Bose',
    email: 'ananya.bose@sequoiacap.com',
    nationality: 'Indian',
    country: 'India',
    roles: ['MENTOR'],
    status: 'confirmed',
    organization: 'Sequoia',
    needsVisa: true,
    expertise: [
      { tagId: 'tag_09', level: 'Deep Expert' },
      { tagId: 'tag_05', level: 'Expert' },
      { tagId: 'tag_01', level: 'Expert' },
    ],
    geographicFocus: 'South Asia',
    industryVertical: 'FinTech & SaaS',
    yearsExperience: 10,
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'mentor_08',
    name: 'Tyler Brooks',
    email: 'tyler.brooks@a16z.com',
    nationality: 'American',
    country: 'United States',
    roles: ['MENTOR'],
    status: 'confirmed',
    organization: 'a16z',
    needsVisa: false,
    expertise: [
      { tagId: 'tag_09', level: 'Deep Expert' },
      { tagId: 'tag_12', level: 'Expert' },
      { tagId: 'tag_13', level: 'Expert' },
    ],
    geographicFocus: 'North America',
    industryVertical: 'AI & Infrastructure',
    yearsExperience: 15,
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'mentor_09',
    name: 'Natalie Foster',
    email: 'natalie.foster@ycombinator.com',
    nationality: 'Canadian',
    country: 'United States',
    roles: ['MENTOR'],
    status: 'confirmed',
    organization: 'Y Combinator',
    needsVisa: false,
    expertise: [
      { tagId: 'tag_09', level: 'Deep Expert' },
      { tagId: 'tag_08', level: 'Expert' },
      { tagId: 'tag_06', level: 'Expert' },
    ],
    geographicFocus: 'North America',
    industryVertical: 'HealthTech & Consumer',
    yearsExperience: 11,
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'mentor_10',
    name: 'Victor Osei',
    email: 'victor.osei@stripe.com',
    nationality: 'Ghanaian',
    country: 'United States',
    roles: ['MENTOR'],
    status: 'confirmed',
    organization: 'Stripe',
    needsVisa: false,
    expertise: [
      { tagId: 'tag_05', level: 'Deep Expert' },
      { tagId: 'tag_13', level: 'Expert' },
      { tagId: 'tag_11', level: 'Expert' },
    ],
    geographicFocus: 'North America',
    industryVertical: 'FinTech & Payments',
    yearsExperience: 10,
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'mentor_11',
    name: 'Hana Nakashima',
    email: 'hana.nakashima@notion.so',
    nationality: 'Japanese',
    country: 'Japan',
    roles: ['MENTOR'],
    status: 'confirmed',
    organization: 'Notion',
    needsVisa: true,
    expertise: [
      { tagId: 'tag_10', level: 'Deep Expert' },
      { tagId: 'tag_01', level: 'Expert' },
      { tagId: 'tag_08', level: 'Expert' },
    ],
    geographicFocus: 'East Asia',
    industryVertical: 'Productivity SaaS',
    yearsExperience: 9,
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'mentor_12',
    name: 'Isabelle Moreau',
    email: 'isabelle.moreau@figma.com',
    nationality: 'French',
    country: 'France',
    roles: ['MENTOR'],
    status: 'confirmed',
    organization: 'Figma',
    needsVisa: true,
    expertise: [
      { tagId: 'tag_10', level: 'Deep Expert' },
      { tagId: 'tag_02', level: 'Expert' },
      { tagId: 'tag_08', level: 'Practitioner' },
    ],
    geographicFocus: 'Europe',
    industryVertical: 'Design & Consumer',
    yearsExperience: 8,
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'mentor_13',
    name: 'Brandon Walsh',
    email: 'brandon.walsh@coinbase.com',
    nationality: 'American',
    country: 'United States',
    roles: ['MENTOR'],
    status: 'confirmed',
    organization: 'Coinbase',
    needsVisa: false,
    expertise: [
      { tagId: 'tag_15', level: 'Deep Expert' },
      { tagId: 'tag_05', level: 'Expert' },
      { tagId: 'tag_14', level: 'Practitioner' },
    ],
    geographicFocus: 'North America',
    industryVertical: 'Web3 & Crypto',
    yearsExperience: 7,
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'mentor_14',
    name: 'Sophia Ritter',
    email: 'sophia.ritter@palantir.com',
    nationality: 'German',
    country: 'Germany',
    roles: ['MENTOR'],
    status: 'confirmed',
    organization: 'Palantir',
    needsVisa: false,
    expertise: [
      { tagId: 'tag_12', level: 'Deep Expert' },
      { tagId: 'tag_13', level: 'Deep Expert' },
      { tagId: 'tag_11', level: 'Expert' },
    ],
    geographicFocus: 'Europe',
    industryVertical: 'Data & AI Ops',
    yearsExperience: 12,
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'mentor_15',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@shopify.com',
    nationality: 'Indian',
    country: 'Canada',
    roles: ['MENTOR'],
    status: 'confirmed',
    organization: 'Shopify',
    needsVisa: false,
    expertise: [
      { tagId: 'tag_02', level: 'Expert' },
      { tagId: 'tag_13', level: 'Expert' },
      { tagId: 'tag_08', level: 'Expert' },
    ],
    geographicFocus: 'North America',
    industryVertical: 'eCommerce & Consumer',
    yearsExperience: 10,
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'mentor_16',
    name: 'Linda Zhou',
    email: 'linda.zhou@sequoiacap.com',
    nationality: 'Chinese',
    country: 'China',
    roles: ['MENTOR'],
    status: 'confirmed',
    organization: 'Sequoia',
    needsVisa: true,
    expertise: [
      { tagId: 'tag_09', level: 'Expert' },
      { tagId: 'tag_04', level: 'Expert' },
      { tagId: 'tag_03', level: 'Expert' },
    ],
    geographicFocus: 'East Asia',
    industryVertical: 'CleanTech & Hardware',
    yearsExperience: 11,
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'mentor_17',
    name: 'Kwame Asante',
    email: 'kwame.asante@ycombinator.com',
    nationality: 'Ghanaian',
    country: 'United States',
    roles: ['MENTOR'],
    status: 'confirmed',
    organization: 'Y Combinator',
    needsVisa: false,
    expertise: [
      { tagId: 'tag_06', level: 'Deep Expert' },
      { tagId: 'tag_09', level: 'Expert' },
      { tagId: 'tag_11', level: 'Expert' },
    ],
    geographicFocus: 'North America',
    industryVertical: 'HealthTech & Global Health',
    yearsExperience: 9,
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'mentor_18',
    name: 'Elena Volkov',
    email: 'elena.volkov@google.com',
    nationality: 'Russian',
    country: 'Germany',
    roles: ['MENTOR'],
    status: 'confirmed',
    organization: 'Google',
    needsVisa: false,
    expertise: [
      { tagId: 'tag_04', level: 'Expert' },
      { tagId: 'tag_03', level: 'Expert' },
      { tagId: 'tag_12', level: 'Practitioner' },
    ],
    geographicFocus: 'Europe',
    industryVertical: 'Hardware & Sustainability',
    yearsExperience: 10,
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'mentor_19',
    name: 'Ravi Sundaram',
    email: 'ravi.sundaram@stripe.com',
    nationality: 'Indian',
    country: 'India',
    roles: ['MENTOR'],
    status: 'confirmed',
    organization: 'Stripe',
    needsVisa: true,
    expertise: [
      { tagId: 'tag_05', level: 'Deep Expert' },
      { tagId: 'tag_11', level: 'Expert' },
      { tagId: 'tag_01', level: 'Expert' },
    ],
    geographicFocus: 'South Asia',
    industryVertical: 'FinTech & Payments',
    yearsExperience: 13,
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'mentor_20',
    name: 'Aiko Tanaka',
    email: 'aiko.tanaka@gssf.org',
    nationality: 'Japanese',
    country: 'Japan',
    roles: ['STUDENT', 'MENTOR'],
    status: 'confirmed',
    organization: 'Independent',
    universityId: 'uni_kaist',
    needsVisa: true,
    expertise: [
      { tagId: 'tag_01', level: 'Practitioner' },
      { tagId: 'tag_13', level: 'Practitioner' },
      { tagId: 'tag_08', level: 'Expert' },
    ],
    geographicFocus: 'East Asia',
    industryVertical: 'SaaS & Operations',
    yearsExperience: 3,
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [
      { programId: 'prog_india_2025', year: 2025, role: 'STUDENT', teamId: 'team_nexus' },
      { programId: 'prog_worlds_2026', year: 2026, role: 'MENTOR' },
    ],
    programIds: ['prog_india_2025', 'prog_worlds_2026'],
  },

  // ── Students ──
  // Atlix (USC)
  {
    personId: 'student_alex_ramos',
    name: 'Alex Ramos',
    email: 'alex.ramos@usc.edu',
    nationality: 'American',
    country: 'United States',
    roles: ['STUDENT'],
    status: 'confirmed',
    universityId: 'uni_usc',
    needsVisa: false,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'student_mia_torres',
    name: 'Mia Torres',
    email: 'mia.torres@usc.edu',
    nationality: 'American',
    country: 'United States',
    roles: ['STUDENT'],
    status: 'confirmed',
    universityId: 'uni_usc',
    needsVisa: false,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'student_derek_chen',
    name: 'Derek Chen',
    email: 'derek.chen@usc.edu',
    nationality: 'American',
    country: 'United States',
    roles: ['STUDENT'],
    status: 'confirmed',
    universityId: 'uni_usc',
    needsVisa: false,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  // Cognate (UC Berkeley)
  {
    personId: 'student_priya_sharma',
    name: 'Priya Sharma',
    email: 'priya.sharma@berkeley.edu',
    nationality: 'Indian',
    country: 'United States',
    roles: ['STUDENT'],
    status: 'confirmed',
    universityId: 'uni_berkeley',
    needsVisa: false,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'student_liam_nguyen',
    name: 'Liam Nguyen',
    email: 'liam.nguyen@berkeley.edu',
    nationality: 'Vietnamese-American',
    country: 'United States',
    roles: ['STUDENT'],
    status: 'confirmed',
    universityId: 'uni_berkeley',
    needsVisa: false,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  // Helion (ETH Zurich)
  {
    personId: 'student_lars_fischer',
    name: 'Lars Fischer',
    email: 'lars.fischer@ethz.ch',
    nationality: 'German',
    country: 'Switzerland',
    roles: ['STUDENT'],
    status: 'confirmed',
    universityId: 'uni_eth',
    needsVisa: true,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'student_anna_mueller',
    name: 'Anna Mueller',
    email: 'anna.mueller@ethz.ch',
    nationality: 'Swiss',
    country: 'Switzerland',
    roles: ['STUDENT'],
    status: 'confirmed',
    universityId: 'uni_eth',
    needsVisa: true,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'student_tobias_braun',
    name: 'Tobias Braun',
    email: 'tobias.braun@ethz.ch',
    nationality: 'Austrian',
    country: 'Switzerland',
    roles: ['STUDENT'],
    status: 'invited',
    universityId: 'uni_eth',
    needsVisa: true,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  // Meridian (Oxford)
  {
    personId: 'student_james_hartley',
    name: 'James Hartley',
    email: 'james.hartley@ox.ac.uk',
    nationality: 'British',
    country: 'United Kingdom',
    roles: ['STUDENT'],
    status: 'confirmed',
    universityId: 'uni_oxford',
    needsVisa: true,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'student_sofia_okonkwo',
    name: 'Sofia Okonkwo',
    email: 'sofia.okonkwo@ox.ac.uk',
    nationality: 'Nigerian-British',
    country: 'United Kingdom',
    roles: ['STUDENT'],
    status: 'confirmed',
    universityId: 'uni_oxford',
    needsVisa: true,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  // Arca (NUS)
  {
    personId: 'student_wei_lin',
    name: 'Wei Lin',
    email: 'wei.lin@nus.edu.sg',
    nationality: 'Chinese-Singaporean',
    country: 'Singapore',
    roles: ['STUDENT'],
    status: 'confirmed',
    universityId: 'uni_nus',
    needsVisa: true,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'student_nadia_tan',
    name: 'Nadia Tan',
    email: 'nadia.tan@nus.edu.sg',
    nationality: 'Singaporean',
    country: 'Singapore',
    roles: ['STUDENT'],
    status: 'confirmed',
    universityId: 'uni_nus',
    needsVisa: true,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'student_farhan_rashid',
    name: 'Farhan Rashid',
    email: 'farhan.rashid@nus.edu.sg',
    nationality: 'Bangladeshi',
    country: 'Singapore',
    roles: ['STUDENT'],
    status: 'invited',
    universityId: 'uni_nus',
    needsVisa: true,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  // Solace (Columbia)
  {
    personId: 'student_elena_vasquez',
    name: 'Elena Vasquez',
    email: 'elena.vasquez@columbia.edu',
    nationality: 'Colombian',
    country: 'United States',
    roles: ['STUDENT'],
    status: 'confirmed',
    universityId: 'uni_columbia',
    needsVisa: false,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'student_omar_hassan',
    name: 'Omar Hassan',
    email: 'omar.hassan@columbia.edu',
    nationality: 'Egyptian',
    country: 'United States',
    roles: ['STUDENT'],
    status: 'confirmed',
    universityId: 'uni_columbia',
    needsVisa: false,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  // Parity (UT Austin)
  {
    personId: 'student_carlos_reyes',
    name: 'Carlos Reyes',
    email: 'carlos.reyes@utexas.edu',
    nationality: 'Mexican-American',
    country: 'United States',
    roles: ['STUDENT'],
    status: 'confirmed',
    universityId: 'uni_utaustin',
    needsVisa: false,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'student_aisha_obi',
    name: 'Aisha Obi',
    email: 'aisha.obi@utexas.edu',
    nationality: 'Nigerian-American',
    country: 'United States',
    roles: ['STUDENT'],
    status: 'confirmed',
    universityId: 'uni_utaustin',
    needsVisa: false,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  // Luma (HKUST)
  {
    personId: 'student_felix_chan',
    name: 'Felix Chan',
    email: 'felix.chan@ust.hk',
    nationality: 'Hong Konger',
    country: 'Hong Kong',
    roles: ['STUDENT'],
    status: 'confirmed',
    universityId: 'uni_hkust',
    needsVisa: true,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'student_iris_ho',
    name: 'Iris Ho',
    email: 'iris.ho@ust.hk',
    nationality: 'Hong Konger',
    country: 'Hong Kong',
    roles: ['STUDENT'],
    status: 'confirmed',
    universityId: 'uni_hkust',
    needsVisa: true,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'student_kevin_lam',
    name: 'Kevin Lam',
    email: 'kevin.lam@ust.hk',
    nationality: 'Hong Konger',
    country: 'Hong Kong',
    roles: ['STUDENT'],
    status: 'invited',
    universityId: 'uni_hkust',
    needsVisa: true,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  // Vanta (Tsinghua)
  {
    personId: 'student_xiao_zhang',
    name: 'Xiao Zhang',
    email: 'xiao.zhang@tsinghua.edu.cn',
    nationality: 'Chinese',
    country: 'China',
    roles: ['STUDENT'],
    status: 'confirmed',
    universityId: 'uni_tsinghua',
    needsVisa: true,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'student_lei_wang',
    name: 'Lei Wang',
    email: 'lei.wang@tsinghua.edu.cn',
    nationality: 'Chinese',
    country: 'China',
    roles: ['STUDENT'],
    status: 'confirmed',
    universityId: 'uni_tsinghua',
    needsVisa: true,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  // Dune (Toronto)
  {
    personId: 'student_ethan_park',
    name: 'Ethan Park',
    email: 'ethan.park@utoronto.ca',
    nationality: 'Korean-Canadian',
    country: 'Canada',
    roles: ['STUDENT'],
    status: 'confirmed',
    universityId: 'uni_toronto',
    needsVisa: false,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'student_claire_martin',
    name: 'Claire Martin',
    email: 'claire.martin@utoronto.ca',
    nationality: 'Canadian',
    country: 'Canada',
    roles: ['STUDENT'],
    status: 'confirmed',
    universityId: 'uni_toronto',
    needsVisa: false,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  {
    personId: 'student_raj_patel',
    name: 'Raj Patel',
    email: 'raj.patel@utoronto.ca',
    nationality: 'Indian-Canadian',
    country: 'Canada',
    roles: ['STUDENT'],
    status: 'confirmed',
    universityId: 'uni_toronto',
    needsVisa: false,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_worlds_2026'],
  },
  // Nexus (IIT Delhi)
  {
    personId: 'student_arjun_singh',
    name: 'Arjun Singh',
    email: 'arjun.singh@iitd.ac.in',
    nationality: 'Indian',
    country: 'India',
    roles: ['STUDENT'],
    status: 'confirmed',
    universityId: 'uni_iitdelhi',
    needsVisa: true,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_india_2025', 'prog_worlds_2026'],
  },
  {
    personId: 'student_aiko_tanaka',
    name: 'Aiko Tanaka',
    email: 'aiko.tanaka@iitd.ac.in',
    nationality: 'Japanese',
    country: 'India',
    roles: ['STUDENT'],
    status: 'confirmed',
    universityId: 'uni_iitdelhi',
    needsVisa: true,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [
      { programId: 'prog_india_2025', year: 2025, role: 'STUDENT', teamId: 'team_nexus' },
    ],
    programIds: ['prog_india_2025', 'prog_worlds_2026'],
  },
  // Orbit (IIT Delhi)
  {
    personId: 'student_kavya_reddy',
    name: 'Kavya Reddy',
    email: 'kavya.reddy@iitd.ac.in',
    nationality: 'Indian',
    country: 'India',
    roles: ['STUDENT'],
    status: 'confirmed',
    universityId: 'uni_iitdelhi',
    needsVisa: true,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_india_2025', 'prog_worlds_2026'],
  },
  {
    personId: 'student_rohan_mehta',
    name: 'Rohan Mehta',
    email: 'rohan.mehta@iitd.ac.in',
    nationality: 'Indian',
    country: 'India',
    roles: ['STUDENT', 'MENTOR'],
    status: 'confirmed',
    universityId: 'uni_iitdelhi',
    needsVisa: true,
    expertise: [
      { tagId: 'tag_01', level: 'Practitioner' },
      { tagId: 'tag_12', level: 'Practitioner' },
    ],
    geographicFocus: 'South Asia',
    industryVertical: 'SaaS',
    yearsExperience: 2,
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [
      { programId: 'prog_worlds_2024', year: 2024, role: 'STUDENT' },
      { programId: 'prog_worlds_2026', year: 2026, role: 'MENTOR' },
    ],
    programIds: ['prog_worlds_2024', 'prog_worlds_2026'],
  },
  // Pragma (Tel Aviv)
  {
    personId: 'student_noa_cohen',
    name: 'Noa Cohen',
    email: 'noa.cohen@tau.ac.il',
    nationality: 'Israeli',
    country: 'Israel',
    roles: ['STUDENT'],
    status: 'confirmed',
    universityId: 'uni_tau',
    needsVisa: true,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_india_2025', 'prog_worlds_2026'],
  },
  {
    personId: 'student_yael_levy',
    name: 'Yael Levy',
    email: 'yael.levy@tau.ac.il',
    nationality: 'Israeli',
    country: 'Israel',
    roles: ['STUDENT'],
    status: 'confirmed',
    universityId: 'uni_tau',
    needsVisa: true,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_india_2025', 'prog_worlds_2026'],
  },
  {
    personId: 'student_amit_katz',
    name: 'Amit Katz',
    email: 'amit.katz@tau.ac.il',
    nationality: 'Israeli',
    country: 'Israel',
    roles: ['STUDENT'],
    status: 'confirmed',
    universityId: 'uni_tau',
    needsVisa: true,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_india_2025', 'prog_worlds_2026'],
  },
  // Flux (Aalto)
  {
    personId: 'student_mikko_virtanen',
    name: 'Mikko Virtanen',
    email: 'mikko.virtanen@aalto.fi',
    nationality: 'Finnish',
    country: 'Finland',
    roles: ['STUDENT'],
    status: 'confirmed',
    universityId: 'uni_aalto',
    needsVisa: false,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_india_2025', 'prog_worlds_2026'],
  },
  {
    personId: 'student_aino_leinonen',
    name: 'Aino Leinonen',
    email: 'aino.leinonen@aalto.fi',
    nationality: 'Finnish',
    country: 'Finland',
    roles: ['STUDENT'],
    status: 'confirmed',
    universityId: 'uni_aalto',
    needsVisa: false,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_india_2025', 'prog_worlds_2026'],
  },
  // Kirin (KAIST)
  {
    personId: 'student_joon_kim',
    name: 'Joon Kim',
    email: 'joon.kim@kaist.ac.kr',
    nationality: 'Korean',
    country: 'South Korea',
    roles: ['STUDENT'],
    status: 'confirmed',
    universityId: 'uni_kaist',
    needsVisa: false,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_korea_2025', 'prog_worlds_2026'],
  },
  {
    personId: 'student_soyeon_lee',
    name: 'Soyeon Lee',
    email: 'soyeon.lee@kaist.ac.kr',
    nationality: 'Korean',
    country: 'South Korea',
    roles: ['STUDENT'],
    status: 'confirmed',
    universityId: 'uni_kaist',
    needsVisa: false,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_korea_2025', 'prog_worlds_2026'],
  },
  // Duplicate pair — James Park (Kirin/KAIST)
  {
    personId: 'student_james_park_1',
    name: 'James Park',
    email: 'james.park@kaist.ac.kr',
    nationality: 'Korean',
    country: 'South Korea',
    roles: ['STUDENT'],
    status: 'confirmed',
    universityId: 'uni_kaist',
    needsVisa: false,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    isDuplicate: true,
    programIds: ['prog_korea_2025', 'prog_worlds_2026'],
  },
  {
    personId: 'student_james_park_2',
    name: 'James Park',
    email: 'jpark@kaist.ac.kr',
    nationality: 'Korean',
    country: 'South Korea',
    roles: ['STUDENT'],
    status: 'confirmed',
    universityId: 'uni_kaist',
    needsVisa: false,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    isDuplicate: true,
    programIds: ['prog_korea_2025', 'prog_worlds_2026'],
  },
  // Sora (KAIST)
  {
    personId: 'student_hyun_cho',
    name: 'Hyun Cho',
    email: 'hyun.cho@kaist.ac.kr',
    nationality: 'Korean',
    country: 'South Korea',
    roles: ['STUDENT'],
    status: 'confirmed',
    universityId: 'uni_kaist',
    needsVisa: false,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [],
    programIds: ['prog_korea_2025', 'prog_worlds_2026'],
  },
  // Returning: Yuna Kim
  {
    personId: 'student_yuna_kim',
    name: 'Yuna Kim',
    email: 'yuna.kim@kaist.ac.kr',
    nationality: 'Korean',
    country: 'South Korea',
    roles: ['STUDENT', 'ORGANIZER'],
    status: 'confirmed',
    universityId: 'uni_kaist',
    needsVisa: false,
    expertise: [],
    conflictWithTeamIds: [],
    conflictWithUniversityIds: [],
    rubricAck: false,
    cohortHistory: [
      { programId: 'prog_korea_2025', year: 2025, role: 'STUDENT' },
      { programId: 'prog_worlds_2026', year: 2026, role: 'ORGANIZER' },
    ],
    programIds: ['prog_korea_2025', 'prog_worlds_2026'],
  },
]

// ─── Pitch Slots ──────────────────────────────────────────────────────────────
// 18 slots: 3 tracks × 2 days × 3 slots
// Day 1: 09:00, 10:00, 11:00 | Day 2: 14:00, 15:00, 16:00
// Track A judges: Sarah Chen (judge_sarah), Daniel Yoon (judge_daniel)
// Track B judges: Marcus Webb (judge_marcus), Leila Ahmadi (judge_leila)
// Track C judges: Priya Nair (judge_priya), Tom Nakamura (judge_tom)
export const pitchSlots: PitchSlot[] = [
  // ── Track A, Day 1 ──
  {
    slotId: 'slot_A_d1_1',
    programId: 'prog_worlds_2026',
    track: 'A',
    day: 1,
    startTime: '09:00',
    endTime: '09:45',
    room: 'Room 101',
    teamId: 'team_atlix',
    judgeIds: ['judge_sarah', 'judge_daniel'],
    conflicts: [],
  },
  {
    slotId: 'slot_A_d1_2',
    programId: 'prog_worlds_2026',
    track: 'A',
    day: 1,
    startTime: '10:00',
    endTime: '10:45',
    room: 'Room 101',
    teamId: 'team_cognate',
    // Sarah Chen double-booked: also assigned to slot_B_d1_2 at same time
    judgeIds: ['judge_sarah', 'judge_daniel'],
    conflicts: [
      {
        type: 'double_booked_judge',
        judgeId: 'judge_sarah',
        description: 'Sarah Chen is scheduled in both Track A Room 101 and Track B Room 102 at 10:00–10:45 on Day 1.',
      },
    ],
  },
  {
    slotId: 'slot_A_d1_3',
    programId: 'prog_worlds_2026',
    track: 'A',
    day: 1,
    startTime: '11:00',
    endTime: '11:45',
    room: 'Room 101',
    teamId: 'team_helion',
    judgeIds: ['judge_sarah', 'judge_daniel'],
    conflicts: [],
  },
  // ── Track A, Day 2 ──
  {
    slotId: 'slot_A_d2_1',
    programId: 'prog_worlds_2026',
    track: 'A',
    day: 2,
    startTime: '14:00',
    endTime: '14:45',
    room: 'Room 101',
    teamId: 'team_meridian',
    judgeIds: ['judge_sarah', 'judge_daniel'],
    conflicts: [],
  },
  {
    slotId: 'slot_A_d2_2',
    programId: 'prog_worlds_2026',
    track: 'A',
    day: 2,
    startTime: '15:00',
    endTime: '15:45',
    room: 'Room 101',
    teamId: 'team_arca',
    judgeIds: ['judge_sarah', 'judge_daniel'],
    conflicts: [],
  },
  {
    slotId: 'slot_A_d2_3',
    programId: 'prog_worlds_2026',
    track: 'A',
    day: 2,
    startTime: '16:00',
    endTime: '16:45',
    room: 'Room 101',
    teamId: 'team_solace',
    judgeIds: ['judge_sarah', 'judge_daniel'],
    conflicts: [],
  },
  // ── Track B, Day 1 ──
  {
    slotId: 'slot_B_d1_1',
    programId: 'prog_worlds_2026',
    track: 'B',
    day: 1,
    startTime: '09:00',
    endTime: '09:45',
    room: 'Room 102',
    teamId: 'team_parity',
    judgeIds: ['judge_marcus', 'judge_leila'],
    conflicts: [],
  },
  {
    slotId: 'slot_B_d1_2',
    programId: 'prog_worlds_2026',
    track: 'B',
    day: 1,
    startTime: '10:00',
    endTime: '10:45',
    room: 'Room 102',
    teamId: 'team_luma',
    // Sarah Chen also assigned here — double booking
    judgeIds: ['judge_marcus', 'judge_leila', 'judge_sarah'],
    conflicts: [],
  },
  {
    slotId: 'slot_B_d1_3',
    programId: 'prog_worlds_2026',
    track: 'B',
    day: 1,
    startTime: '11:00',
    endTime: '11:45',
    room: 'Room 102',
    teamId: 'team_vanta',
    judgeIds: ['judge_marcus', 'judge_leila'],
    conflicts: [],
  },
  // ── Track B, Day 2 ──
  {
    slotId: 'slot_B_d2_1',
    programId: 'prog_worlds_2026',
    track: 'B',
    day: 2,
    startTime: '14:00',
    endTime: '14:45',
    room: 'Room 102',
    teamId: 'team_dune',
    judgeIds: ['judge_marcus', 'judge_leila'],
    conflicts: [],
  },
  {
    slotId: 'slot_B_d2_2',
    programId: 'prog_worlds_2026',
    track: 'B',
    day: 2,
    startTime: '15:00',
    endTime: '15:45',
    room: 'Room 102',
    teamId: 'team_nexus',
    judgeIds: ['judge_marcus', 'judge_leila'],
    conflicts: [],
  },
  {
    slotId: 'slot_B_d2_3',
    programId: 'prog_worlds_2026',
    track: 'B',
    day: 2,
    startTime: '16:00',
    endTime: '16:45',
    room: 'Room 102',
    // Empty slot
    judgeIds: ['judge_marcus', 'judge_leila'],
    conflicts: [],
  },
  // ── Track C, Day 1 ──
  {
    slotId: 'slot_C_d1_1',
    programId: 'prog_worlds_2026',
    track: 'C',
    day: 1,
    startTime: '09:00',
    endTime: '09:45',
    room: 'Room 103',
    teamId: 'team_orbit',
    judgeIds: ['judge_priya', 'judge_tom'],
    conflicts: [],
  },
  {
    slotId: 'slot_C_d1_2',
    programId: 'prog_worlds_2026',
    track: 'C',
    day: 1,
    startTime: '10:00',
    endTime: '10:45',
    room: 'Room 103',
    teamId: 'team_pragma',
    judgeIds: ['judge_priya', 'judge_tom'],
    conflicts: [],
  },
  {
    slotId: 'slot_C_d1_3',
    programId: 'prog_worlds_2026',
    track: 'C',
    day: 1,
    startTime: '11:00',
    endTime: '11:45',
    room: 'Room 103',
    teamId: 'team_flux',
    judgeIds: ['judge_priya', 'judge_tom'],
    conflicts: [],
  },
  // ── Track C, Day 2 ──
  {
    slotId: 'slot_C_d2_1',
    programId: 'prog_worlds_2026',
    track: 'C',
    day: 2,
    startTime: '14:00',
    endTime: '14:45',
    room: 'Room 103',
    teamId: 'team_kirin',
    judgeIds: ['judge_priya', 'judge_tom'],
    // Tom Nakamura has conflict of interest with Kirin
    conflicts: [
      {
        type: 'conflict_of_interest',
        judgeId: 'judge_tom',
        description: 'Tom Nakamura declared a conflict of interest with team Kirin (prior investment relationship).',
      },
    ],
  },
  {
    slotId: 'slot_C_d2_2',
    programId: 'prog_worlds_2026',
    track: 'C',
    day: 2,
    startTime: '15:00',
    endTime: '15:45',
    room: 'Room 103',
    teamId: 'team_sora',
    judgeIds: ['judge_priya', 'judge_tom'],
    conflicts: [],
  },
  {
    slotId: 'slot_C_d2_3',
    programId: 'prog_worlds_2026',
    track: 'C',
    day: 2,
    startTime: '16:00',
    endTime: '16:45',
    room: 'Room 103',
    // Empty slot
    judgeIds: ['judge_priya', 'judge_tom'],
    conflicts: [],
  },
]

// ─── Scores ───────────────────────────────────────────────────────────────────
// Track A: all 6 teams scored by Sarah Chen and Daniel Yoon (partial — not closed)
// Track B: 2 teams scored by Marcus Webb only
// Track C: no scores
function calcTotal(d: { innovation: number; market: number; team: number; traction: number }): number {
  return Math.round((d.innovation * 0.3 + d.market * 0.25 + d.team * 0.25 + d.traction * 0.2) * 10) / 10
}

export const scores: Score[] = [
  // Sarah Chen — Track A
  {
    scoreId: 'score_sarah_atlix',
    judgeId: 'judge_sarah',
    teamId: 'team_atlix',
    programId: 'prog_worlds_2026',
    dimensions: { innovation: 8, market: 8, team: 9, traction: 7 },
    total: calcTotal({ innovation: 8, market: 8, team: 9, traction: 7 }),
    submittedAt: '2026-04-10T10:00:00Z',
    track: 'A',
  },
  {
    scoreId: 'score_sarah_cognate',
    judgeId: 'judge_sarah',
    teamId: 'team_cognate',
    programId: 'prog_worlds_2026',
    dimensions: { innovation: 9, market: 7, team: 8, traction: 8 },
    total: calcTotal({ innovation: 9, market: 7, team: 8, traction: 8 }),
    submittedAt: '2026-04-10T10:50:00Z',
    track: 'A',
  },
  {
    scoreId: 'score_sarah_helion',
    judgeId: 'judge_sarah',
    teamId: 'team_helion',
    programId: 'prog_worlds_2026',
    dimensions: { innovation: 9, market: 7, team: 7, traction: 6 },
    total: calcTotal({ innovation: 9, market: 7, team: 7, traction: 6 }),
    submittedAt: '2026-04-10T11:50:00Z',
    track: 'A',
  },
  {
    scoreId: 'score_sarah_meridian',
    judgeId: 'judge_sarah',
    teamId: 'team_meridian',
    programId: 'prog_worlds_2026',
    dimensions: { innovation: 7, market: 9, team: 8, traction: 8 },
    total: calcTotal({ innovation: 7, market: 9, team: 8, traction: 8 }),
    submittedAt: '2026-04-11T14:50:00Z',
    track: 'A',
  },
  {
    scoreId: 'score_sarah_arca',
    judgeId: 'judge_sarah',
    teamId: 'team_arca',
    programId: 'prog_worlds_2026',
    dimensions: { innovation: 8, market: 8, team: 7, traction: 9 },
    total: calcTotal({ innovation: 8, market: 8, team: 7, traction: 9 }),
    submittedAt: '2026-04-11T15:50:00Z',
    track: 'A',
  },
  {
    scoreId: 'score_sarah_solace',
    judgeId: 'judge_sarah',
    teamId: 'team_solace',
    programId: 'prog_worlds_2026',
    dimensions: { innovation: 9, market: 8, team: 8, traction: 7 },
    total: calcTotal({ innovation: 9, market: 8, team: 8, traction: 7 }),
    submittedAt: '2026-04-11T16:50:00Z',
    track: 'A',
  },
  // Daniel Yoon — Track A
  {
    scoreId: 'score_daniel_atlix',
    judgeId: 'judge_daniel',
    teamId: 'team_atlix',
    programId: 'prog_worlds_2026',
    dimensions: { innovation: 7, market: 8, team: 9, traction: 8 },
    total: calcTotal({ innovation: 7, market: 8, team: 9, traction: 8 }),
    submittedAt: '2026-04-10T10:05:00Z',
    track: 'A',
  },
  {
    scoreId: 'score_daniel_cognate',
    judgeId: 'judge_daniel',
    teamId: 'team_cognate',
    programId: 'prog_worlds_2026',
    dimensions: { innovation: 8, market: 8, team: 8, traction: 9 },
    total: calcTotal({ innovation: 8, market: 8, team: 8, traction: 9 }),
    submittedAt: '2026-04-10T10:55:00Z',
    track: 'A',
  },
  {
    scoreId: 'score_daniel_helion',
    judgeId: 'judge_daniel',
    teamId: 'team_helion',
    programId: 'prog_worlds_2026',
    dimensions: { innovation: 8, market: 6, team: 7, traction: 6 },
    total: calcTotal({ innovation: 8, market: 6, team: 7, traction: 6 }),
    submittedAt: '2026-04-10T11:55:00Z',
    track: 'A',
  },
  {
    scoreId: 'score_daniel_meridian',
    judgeId: 'judge_daniel',
    teamId: 'team_meridian',
    programId: 'prog_worlds_2026',
    dimensions: { innovation: 7, market: 9, team: 9, traction: 8 },
    total: calcTotal({ innovation: 7, market: 9, team: 9, traction: 8 }),
    submittedAt: '2026-04-11T14:55:00Z',
    track: 'A',
  },
  {
    scoreId: 'score_daniel_arca',
    judgeId: 'judge_daniel',
    teamId: 'team_arca',
    programId: 'prog_worlds_2026',
    dimensions: { innovation: 7, market: 8, team: 8, traction: 8 },
    total: calcTotal({ innovation: 7, market: 8, team: 8, traction: 8 }),
    submittedAt: '2026-04-11T15:55:00Z',
    track: 'A',
  },
  {
    scoreId: 'score_daniel_solace',
    judgeId: 'judge_daniel',
    teamId: 'team_solace',
    programId: 'prog_worlds_2026',
    dimensions: { innovation: 9, market: 7, team: 8, traction: 7 },
    total: calcTotal({ innovation: 9, market: 7, team: 8, traction: 7 }),
    submittedAt: '2026-04-11T16:55:00Z',
    track: 'A',
  },
  // Marcus Webb — Track B (only 2 teams)
  {
    scoreId: 'score_marcus_parity',
    judgeId: 'judge_marcus',
    teamId: 'team_parity',
    programId: 'prog_worlds_2026',
    dimensions: { innovation: 8, market: 7, team: 8, traction: 7 },
    total: calcTotal({ innovation: 8, market: 7, team: 8, traction: 7 }),
    submittedAt: '2026-04-10T09:50:00Z',
    track: 'B',
  },
  {
    scoreId: 'score_marcus_luma',
    judgeId: 'judge_marcus',
    teamId: 'team_luma',
    programId: 'prog_worlds_2026',
    dimensions: { innovation: 7, market: 8, team: 7, traction: 9 },
    total: calcTotal({ innovation: 7, market: 8, team: 7, traction: 9 }),
    submittedAt: '2026-04-10T10:50:00Z',
    track: 'B',
  },
]

// ─── Mentor Matches ───────────────────────────────────────────────────────────
// Pre-generated top-3 matches per team
// Logic: tagOverlapScore + geographyScore + stageScore (see matching.ts for algo)
export const mentorMatches: MentorMatch[] = [
  // team_atlix needs: tag_08 (GTM), tag_01 (B2B SaaS), tag_09 (Fundraising), Pre-seed, North America
  { mentorId: 'mentor_06', teamId: 'team_atlix', score: 85, tagOverlapScore: 60, geographyScore: 10, stageScore: 15, matchedTagIds: ['tag_01', 'tag_09'], rank: 1 },
  { mentorId: 'mentor_01', teamId: 'team_atlix', score: 80, tagOverlapScore: 60, geographyScore: 10, stageScore: 10, matchedTagIds: ['tag_01', 'tag_08'], rank: 2 },
  { mentorId: 'mentor_09', teamId: 'team_atlix', score: 67, tagOverlapScore: 40, geographyScore: 10, stageScore: 17, matchedTagIds: ['tag_09', 'tag_08'], rank: 3 },

  // team_cognate needs: tag_12 (AI/ML), tag_10 (Product), tag_01 (B2B SaaS), Seed, North America
  { mentorId: 'mentor_04', teamId: 'team_cognate', score: 90, tagOverlapScore: 60, geographyScore: 10, stageScore: 20, matchedTagIds: ['tag_12', 'tag_10', 'tag_01'], rank: 1 },
  { mentorId: 'mentor_01', teamId: 'team_cognate', score: 73, tagOverlapScore: 53, geographyScore: 10, stageScore: 10, matchedTagIds: ['tag_01', 'tag_10'], rank: 2 },
  { mentorId: 'mentor_11', teamId: 'team_cognate', score: 66, tagOverlapScore: 40, geographyScore: 0, stageScore: 26, matchedTagIds: ['tag_01', 'tag_10'], rank: 3 },

  // team_helion needs: tag_03 (Hardware), tag_04 (Climate Tech), tag_09 (Fundraising), Pre-seed, Europe
  { mentorId: 'mentor_18', teamId: 'team_helion', score: 80, tagOverlapScore: 53, geographyScore: 10, stageScore: 17, matchedTagIds: ['tag_03', 'tag_04'], rank: 1 },
  { mentorId: 'mentor_16', teamId: 'team_helion', score: 77, tagOverlapScore: 60, geographyScore: 0, stageScore: 17, matchedTagIds: ['tag_03', 'tag_04', 'tag_09'], rank: 2 },
  { mentorId: 'mentor_09', teamId: 'team_helion', score: 57, tagOverlapScore: 20, geographyScore: 10, stageScore: 27, matchedTagIds: ['tag_09'], rank: 3 },

  // team_meridian needs: tag_05 (FinTech), tag_14 (Legal), tag_11 (BD), Seed, Europe
  { mentorId: 'mentor_10', teamId: 'team_meridian', score: 78, tagOverlapScore: 53, geographyScore: 10, stageScore: 15, matchedTagIds: ['tag_05', 'tag_11'], rank: 1 },
  { mentorId: 'mentor_13', teamId: 'team_meridian', score: 65, tagOverlapScore: 40, geographyScore: 10, stageScore: 15, matchedTagIds: ['tag_05', 'tag_14'], rank: 2 },
  { mentorId: 'mentor_07', teamId: 'team_meridian', score: 55, tagOverlapScore: 20, geographyScore: 0, stageScore: 35, matchedTagIds: ['tag_05'], rank: 3 },

  // team_arca needs: tag_02 (Consumer), tag_08 (GTM), tag_10 (Product), Pre-seed, Southeast Asia
  { mentorId: 'mentor_05', teamId: 'team_arca', score: 88, tagOverlapScore: 53, geographyScore: 10, stageScore: 25, matchedTagIds: ['tag_02', 'tag_08'], rank: 1 },
  { mentorId: 'mentor_02', teamId: 'team_arca', score: 75, tagOverlapScore: 53, geographyScore: 10, stageScore: 12, matchedTagIds: ['tag_02', 'tag_08'], rank: 2 },
  { mentorId: 'mentor_12', teamId: 'team_arca', score: 60, tagOverlapScore: 40, geographyScore: 0, stageScore: 20, matchedTagIds: ['tag_02', 'tag_10'], rank: 3 },

  // team_solace needs: tag_06 (HealthTech), tag_09 (Fundraising), tag_12 (AI/ML), Pre-seed, North America
  { mentorId: 'mentor_17', teamId: 'team_solace', score: 87, tagOverlapScore: 53, geographyScore: 10, stageScore: 24, matchedTagIds: ['tag_06', 'tag_09'], rank: 1 },
  { mentorId: 'mentor_09', teamId: 'team_solace', score: 80, tagOverlapScore: 53, geographyScore: 10, stageScore: 17, matchedTagIds: ['tag_09', 'tag_06'], rank: 2 },
  { mentorId: 'mentor_04', teamId: 'team_solace', score: 63, tagOverlapScore: 40, geographyScore: 10, stageScore: 13, matchedTagIds: ['tag_12'], rank: 3 },

  // team_parity needs: tag_15 (Web3), tag_14 (Legal), tag_09 (Fundraising), Seed, North America
  { mentorId: 'mentor_13', teamId: 'team_parity', score: 73, tagOverlapScore: 53, geographyScore: 10, stageScore: 10, matchedTagIds: ['tag_15', 'tag_14'], rank: 1 },
  { mentorId: 'mentor_08', teamId: 'team_parity', score: 55, tagOverlapScore: 20, geographyScore: 10, stageScore: 25, matchedTagIds: ['tag_09'], rank: 2 },
  { mentorId: 'mentor_06', teamId: 'team_parity', score: 50, tagOverlapScore: 20, geographyScore: 10, stageScore: 20, matchedTagIds: ['tag_09'], rank: 3 },

  // team_luma needs: tag_02 (Consumer), tag_07 (EdTech), tag_08 (GTM), Pre-seed, East Asia
  { mentorId: 'mentor_03', teamId: 'team_luma', score: 82, tagOverlapScore: 53, geographyScore: 0, stageScore: 29, matchedTagIds: ['tag_07', 'tag_02'], rank: 1 },
  { mentorId: 'mentor_05', teamId: 'team_luma', score: 77, tagOverlapScore: 53, geographyScore: 10, stageScore: 14, matchedTagIds: ['tag_02', 'tag_08'], rank: 2 },
  { mentorId: 'mentor_11', teamId: 'team_luma', score: 55, tagOverlapScore: 20, geographyScore: 10, stageScore: 25, matchedTagIds: ['tag_08'], rank: 3 },

  // team_vanta needs: tag_12 (AI/ML), tag_01 (B2B SaaS), tag_13 (Ops), Seed, East Asia
  { mentorId: 'mentor_14', teamId: 'team_vanta', score: 88, tagOverlapScore: 53, geographyScore: 0, stageScore: 35, matchedTagIds: ['tag_12', 'tag_13'], rank: 1 },
  { mentorId: 'mentor_04', teamId: 'team_vanta', score: 80, tagOverlapScore: 53, geographyScore: 10, stageScore: 17, matchedTagIds: ['tag_12', 'tag_01'], rank: 2 },
  { mentorId: 'mentor_08', teamId: 'team_vanta', score: 68, tagOverlapScore: 40, geographyScore: 10, stageScore: 18, matchedTagIds: ['tag_12', 'tag_13'], rank: 3 },

  // team_dune needs: tag_04 (Climate Tech), tag_03 (Hardware), tag_11 (BD), Pre-seed, North America
  { mentorId: 'mentor_16', teamId: 'team_dune', score: 82, tagOverlapScore: 53, geographyScore: 0, stageScore: 29, matchedTagIds: ['tag_04', 'tag_03'], rank: 1 },
  { mentorId: 'mentor_18', teamId: 'team_dune', score: 76, tagOverlapScore: 53, geographyScore: 0, stageScore: 23, matchedTagIds: ['tag_04', 'tag_03'], rank: 2 },
  { mentorId: 'mentor_10', teamId: 'team_dune', score: 57, tagOverlapScore: 20, geographyScore: 10, stageScore: 27, matchedTagIds: ['tag_11'], rank: 3 },

  // team_nexus needs: tag_01 (B2B SaaS), tag_13 (Ops), tag_08 (GTM), Seed, South Asia
  { mentorId: 'mentor_07', teamId: 'team_nexus', score: 85, tagOverlapScore: 53, geographyScore: 10, stageScore: 22, matchedTagIds: ['tag_01', 'tag_09'], rank: 1 },
  { mentorId: 'mentor_19', teamId: 'team_nexus', score: 78, tagOverlapScore: 53, geographyScore: 10, stageScore: 15, matchedTagIds: ['tag_01', 'tag_11'], rank: 2 },
  { mentorId: 'mentor_20', teamId: 'team_nexus', score: 65, tagOverlapScore: 40, geographyScore: 10, stageScore: 15, matchedTagIds: ['tag_01', 'tag_13', 'tag_08'], rank: 3 },

  // team_orbit needs: tag_12 (AI/ML), tag_10 (Product), tag_09 (Fundraising), Pre-seed, South Asia
  { mentorId: 'mentor_04', teamId: 'team_orbit', score: 85, tagOverlapScore: 60, geographyScore: 10, stageScore: 15, matchedTagIds: ['tag_12', 'tag_10'], rank: 1 },
  { mentorId: 'mentor_07', teamId: 'team_orbit', score: 72, tagOverlapScore: 40, geographyScore: 10, stageScore: 22, matchedTagIds: ['tag_09'], rank: 2 },
  { mentorId: 'mentor_08', teamId: 'team_orbit', score: 67, tagOverlapScore: 40, geographyScore: 10, stageScore: 17, matchedTagIds: ['tag_09', 'tag_12'], rank: 3 },

  // team_pragma needs: tag_05 (FinTech), tag_12 (AI/ML), tag_11 (BD), Pre-seed, South Asia (Israel → close enough)
  { mentorId: 'mentor_10', teamId: 'team_pragma', score: 78, tagOverlapScore: 53, geographyScore: 10, stageScore: 15, matchedTagIds: ['tag_05', 'tag_11'], rank: 1 },
  { mentorId: 'mentor_04', teamId: 'team_pragma', score: 70, tagOverlapScore: 40, geographyScore: 10, stageScore: 20, matchedTagIds: ['tag_12'], rank: 2 },
  { mentorId: 'mentor_19', teamId: 'team_pragma', score: 65, tagOverlapScore: 40, geographyScore: 10, stageScore: 15, matchedTagIds: ['tag_05', 'tag_11'], rank: 3 },

  // team_flux needs: tag_04 (Climate), tag_03 (Hardware), tag_13 (Ops), Seed, Europe
  { mentorId: 'mentor_14', teamId: 'team_flux', score: 82, tagOverlapScore: 53, geographyScore: 10, stageScore: 19, matchedTagIds: ['tag_13'], rank: 1 },
  { mentorId: 'mentor_18', teamId: 'team_flux', score: 80, tagOverlapScore: 53, geographyScore: 10, stageScore: 17, matchedTagIds: ['tag_04', 'tag_03'], rank: 2 },
  { mentorId: 'mentor_16', teamId: 'team_flux', score: 72, tagOverlapScore: 60, geographyScore: 0, stageScore: 12, matchedTagIds: ['tag_04', 'tag_03'], rank: 3 },

  // team_kirin needs: tag_03 (Hardware), tag_12 (AI/ML), tag_08 (GTM), Seed, East Asia
  { mentorId: 'mentor_16', teamId: 'team_kirin', score: 75, tagOverlapScore: 40, geographyScore: 10, stageScore: 25, matchedTagIds: ['tag_03'], rank: 1 },
  { mentorId: 'mentor_04', teamId: 'team_kirin', score: 70, tagOverlapScore: 40, geographyScore: 10, stageScore: 20, matchedTagIds: ['tag_12'], rank: 2 },
  { mentorId: 'mentor_11', teamId: 'team_kirin', score: 55, tagOverlapScore: 20, geographyScore: 10, stageScore: 25, matchedTagIds: ['tag_08'], rank: 3 },

  // team_sora needs: tag_02 (Consumer), tag_07 (EdTech), tag_10 (Product), Pre-seed, East Asia
  { mentorId: 'mentor_03', teamId: 'team_sora', score: 85, tagOverlapScore: 60, geographyScore: 0, stageScore: 25, matchedTagIds: ['tag_07', 'tag_02', 'tag_10'], rank: 1 },
  { mentorId: 'mentor_11', teamId: 'team_sora', score: 70, tagOverlapScore: 40, geographyScore: 10, stageScore: 20, matchedTagIds: ['tag_10'], rank: 2 },
  { mentorId: 'mentor_02', teamId: 'team_sora', score: 62, tagOverlapScore: 40, geographyScore: 0, stageScore: 22, matchedTagIds: ['tag_02', 'tag_07'], rank: 3 },
]

export const visaLetters: VisaLetter[] = []
